# Generated by Django 5.2.7 on 2025-10-23 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContasPagar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(help_text='Descrição da conta a pagar', max_length=200, verbose_name='Descrição')),
                ('valor', models.DecimalField(decimal_places=2, help_text='Valor da conta a pagar', max_digits=10, verbose_name='Valor')),
                ('vencimento', models.DateField(help_text='Data de vencimento da conta a pagar', verbose_name='Vencimento')),
                ('pago', models.BooleanField(default=False, help_text='Status de pagamento da conta a pagar', verbose_name='Pago')),
            ],
        ),
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(help_text='Descrição da despesa', max_length=200, verbose_name='Descrição')),
                ('valor', models.DecimalField(decimal_places=2, help_text='Valor da despesa', max_digits=10, verbose_name='Valor')),
                ('data', models.DateField(help_text='Data da despesa', verbose_name='Data')),
            ],
        ),
        migrations.CreateModel(
            name='Investimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(help_text='Descrição do investimento', max_length=200, verbose_name='Descrição')),
                ('valor', models.DecimalField(decimal_places=2, help_text='Valor do investimento', max_digits=10, verbose_name='Valor')),
                ('data', models.DateField(help_text='Data do investimento', verbose_name='Data')),
            ],
        ),
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(help_text='Descrição da receita', max_length=200, verbose_name='Descrição')),
                ('valor', models.DecimalField(decimal_places=2, help_text='Valor da receita', max_digits=10, verbose_name='Valor')),
                ('data', models.DateField(help_text='Data da receita', verbose_name='Data')),
            ],
        ),
    ]
