# Generated by Django 5.2.7 on 2025-10-23 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economia', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contaspagar',
            options={'verbose_name': 'Conta a Pagar', 'verbose_name_plural': 'Contas a Pagar'},
        ),
        migrations.AddField(
            model_name='despesa',
            name='investimento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='despesas', to='economia.investimento'),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='data',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='descricao',
            field=models.CharField(max_length=200, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='investimento',
            name='data',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='investimento',
            name='descricao',
            field=models.CharField(max_length=200, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='investimento',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='receita',
            name='data',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='receita',
            name='descricao',
            field=models.CharField(max_length=200, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='receita',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
