# Generated by Django 5.2.7 on 2025-10-23 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economia', '0002_alter_contaspagar_options_despesa_investimento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='investimento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='despesas', to='economia.investimento', verbose_name='Investimento relacionado'),
        ),
    ]
