# Generated by Django 5.2.7 on 2025-10-23 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economia', '0003_alter_despesa_investimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='contaspagar',
            name='recorrente',
            field=models.BooleanField(default=False, help_text='Indica se a conta é recorrente', verbose_name='Recorrente'),
        ),
    ]
